# Generated by Django 4.2.18 on 2025-03-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_national_team_flag'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_player',
            field=models.ManyToManyField(related_name='fans', to='players.player'),
        ),
    ]
