# Generated by Django 4.2.18 on 2025-02-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='citienship',
            new_name='citizenship',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='jerser_number',
            new_name='jersey_number',
        ),
    ]
