# Generated by Django 4.2.18 on 2025-02-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_citienship_player_citizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='national_team_flag',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
